#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Taxi")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertVoditeli(Voditeli instance);
    partial void UpdateVoditeli(Voditeli instance);
    partial void DeleteVoditeli(Voditeli instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::Taxi1.Properties.Settings.Default.TaxiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Voditeli> Voditeli
		{
			get
			{
				return this.GetTable<Voditeli>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Voditeli")]
	public partial class Voditeli : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Voditel;
		
		private string _FIO;
		
		private System.DateTime _Date_rozdeniya;
		
		private string _seriya_pasporta;
		
		private string _nomer_pasporta;
		
		private System.DateTime _Date_vydan_pasport;
		
		private string _Marka_mashiny;
		
		private string _tsvet;
		
		private string _kategoriya_vozhdeniya;
		
		private string _Nomer_prav;
		
		private System.DateTime _Data_vidachi;
		
		private System.DateTime _okonchaniye_prav;
		
		private string _Nomer_mash;
		
		private string _Vidan_pasport;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VoditelChanging(int value);
    partial void OnID_VoditelChanged();
    partial void OnFIOChanging(string value);
    partial void OnFIOChanged();
    partial void OnDate_rozdeniyaChanging(System.DateTime value);
    partial void OnDate_rozdeniyaChanged();
    partial void Onseriya_pasportaChanging(string value);
    partial void Onseriya_pasportaChanged();
    partial void Onnomer_pasportaChanging(string value);
    partial void Onnomer_pasportaChanged();
    partial void OnDate_vydan_pasportChanging(System.DateTime value);
    partial void OnDate_vydan_pasportChanged();
    partial void OnMarka_mashinyChanging(string value);
    partial void OnMarka_mashinyChanged();
    partial void OntsvetChanging(string value);
    partial void OntsvetChanged();
    partial void Onkategoriya_vozhdeniyaChanging(string value);
    partial void Onkategoriya_vozhdeniyaChanged();
    partial void OnNomer_pravChanging(string value);
    partial void OnNomer_pravChanged();
    partial void OnData_vidachiChanging(System.DateTime value);
    partial void OnData_vidachiChanged();
    partial void Onokonchaniye_pravChanging(System.DateTime value);
    partial void Onokonchaniye_pravChanged();
    partial void OnNomer_mashChanging(string value);
    partial void OnNomer_mashChanged();
    partial void OnVidan_pasportChanging(string value);
    partial void OnVidan_pasportChanged();
    #endregion
		
		public Voditeli()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Voditel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Voditel
		{
			get
			{
				return this._ID_Voditel;
			}
			set
			{
				if ((this._ID_Voditel != value))
				{
					this.OnID_VoditelChanging(value);
					this.SendPropertyChanging();
					this._ID_Voditel = value;
					this.SendPropertyChanged("ID_Voditel");
					this.OnID_VoditelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this.OnFIOChanging(value);
					this.SendPropertyChanging();
					this._FIO = value;
					this.SendPropertyChanged("FIO");
					this.OnFIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date rozdeniya]", Storage="_Date_rozdeniya", DbType="Date NOT NULL")]
		public System.DateTime Date_rozdeniya
		{
			get
			{
				return this._Date_rozdeniya;
			}
			set
			{
				if ((this._Date_rozdeniya != value))
				{
					this.OnDate_rozdeniyaChanging(value);
					this.SendPropertyChanging();
					this._Date_rozdeniya = value;
					this.SendPropertyChanged("Date_rozdeniya");
					this.OnDate_rozdeniyaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[seriya pasporta]", Storage="_seriya_pasporta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string seriya_pasporta
		{
			get
			{
				return this._seriya_pasporta;
			}
			set
			{
				if ((this._seriya_pasporta != value))
				{
					this.Onseriya_pasportaChanging(value);
					this.SendPropertyChanging();
					this._seriya_pasporta = value;
					this.SendPropertyChanged("seriya_pasporta");
					this.Onseriya_pasportaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[nomer pasporta]", Storage="_nomer_pasporta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nomer_pasporta
		{
			get
			{
				return this._nomer_pasporta;
			}
			set
			{
				if ((this._nomer_pasporta != value))
				{
					this.Onnomer_pasportaChanging(value);
					this.SendPropertyChanging();
					this._nomer_pasporta = value;
					this.SendPropertyChanged("nomer_pasporta");
					this.Onnomer_pasportaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Date vydan pasport]", Storage="_Date_vydan_pasport", DbType="Date NOT NULL")]
		public System.DateTime Date_vydan_pasport
		{
			get
			{
				return this._Date_vydan_pasport;
			}
			set
			{
				if ((this._Date_vydan_pasport != value))
				{
					this.OnDate_vydan_pasportChanging(value);
					this.SendPropertyChanging();
					this._Date_vydan_pasport = value;
					this.SendPropertyChanged("Date_vydan_pasport");
					this.OnDate_vydan_pasportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Marka mashiny]", Storage="_Marka_mashiny", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Marka_mashiny
		{
			get
			{
				return this._Marka_mashiny;
			}
			set
			{
				if ((this._Marka_mashiny != value))
				{
					this.OnMarka_mashinyChanging(value);
					this.SendPropertyChanging();
					this._Marka_mashiny = value;
					this.SendPropertyChanged("Marka_mashiny");
					this.OnMarka_mashinyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tsvet", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tsvet
		{
			get
			{
				return this._tsvet;
			}
			set
			{
				if ((this._tsvet != value))
				{
					this.OntsvetChanging(value);
					this.SendPropertyChanging();
					this._tsvet = value;
					this.SendPropertyChanged("tsvet");
					this.OntsvetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[kategoriya vozhdeniya]", Storage="_kategoriya_vozhdeniya", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string kategoriya_vozhdeniya
		{
			get
			{
				return this._kategoriya_vozhdeniya;
			}
			set
			{
				if ((this._kategoriya_vozhdeniya != value))
				{
					this.Onkategoriya_vozhdeniyaChanging(value);
					this.SendPropertyChanging();
					this._kategoriya_vozhdeniya = value;
					this.SendPropertyChanged("kategoriya_vozhdeniya");
					this.Onkategoriya_vozhdeniyaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nomer prav]", Storage="_Nomer_prav", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nomer_prav
		{
			get
			{
				return this._Nomer_prav;
			}
			set
			{
				if ((this._Nomer_prav != value))
				{
					this.OnNomer_pravChanging(value);
					this.SendPropertyChanging();
					this._Nomer_prav = value;
					this.SendPropertyChanged("Nomer_prav");
					this.OnNomer_pravChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Data vidachi]", Storage="_Data_vidachi", DbType="Date NOT NULL")]
		public System.DateTime Data_vidachi
		{
			get
			{
				return this._Data_vidachi;
			}
			set
			{
				if ((this._Data_vidachi != value))
				{
					this.OnData_vidachiChanging(value);
					this.SendPropertyChanging();
					this._Data_vidachi = value;
					this.SendPropertyChanged("Data_vidachi");
					this.OnData_vidachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[okonchaniye prav]", Storage="_okonchaniye_prav", DbType="Date NOT NULL")]
		public System.DateTime okonchaniye_prav
		{
			get
			{
				return this._okonchaniye_prav;
			}
			set
			{
				if ((this._okonchaniye_prav != value))
				{
					this.Onokonchaniye_pravChanging(value);
					this.SendPropertyChanging();
					this._okonchaniye_prav = value;
					this.SendPropertyChanged("okonchaniye_prav");
					this.Onokonchaniye_pravChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomer_mash", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nomer_mash
		{
			get
			{
				return this._Nomer_mash;
			}
			set
			{
				if ((this._Nomer_mash != value))
				{
					this.OnNomer_mashChanging(value);
					this.SendPropertyChanging();
					this._Nomer_mash = value;
					this.SendPropertyChanged("Nomer_mash");
					this.OnNomer_mashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vidan_pasport", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Vidan_pasport
		{
			get
			{
				return this._Vidan_pasport;
			}
			set
			{
				if ((this._Vidan_pasport != value))
				{
					this.OnVidan_pasportChanging(value);
					this.SendPropertyChanging();
					this._Vidan_pasport = value;
					this.SendPropertyChanged("Vidan_pasport");
					this.OnVidan_pasportChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
