#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taxi1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Taxi")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertZakaz(Zakaz instance);
    partial void UpdateZakaz(Zakaz instance);
    partial void DeleteZakaz(Zakaz instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Taxi1.Properties.Settings.Default.TaxiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Zakaz> Zakaz
		{
			get
			{
				return this.GetTable<Zakaz>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zakaz")]
	public partial class Zakaz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Zakaz;
		
		private string _Nomer_Tel;
		
		private string _adres_dostavki;
		
		private string _adres_otpravki;
		
		private bool _Statyz_zakaz;
		
		private int _Tsena_proyeezda;
		
		private string _Oplata;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ZakazChanging(int value);
    partial void OnID_ZakazChanged();
    partial void OnNomer_TelChanging(string value);
    partial void OnNomer_TelChanged();
    partial void Onadres_dostavkiChanging(string value);
    partial void Onadres_dostavkiChanged();
    partial void Onadres_otpravkiChanging(string value);
    partial void Onadres_otpravkiChanged();
    partial void OnStatyz_zakazChanging(bool value);
    partial void OnStatyz_zakazChanged();
    partial void OnTsena_proyeezdaChanging(int value);
    partial void OnTsena_proyeezdaChanged();
    partial void OnOplataChanging(string value);
    partial void OnOplataChanged();
    #endregion
		
		public Zakaz()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Zakaz", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Zakaz
		{
			get
			{
				return this._ID_Zakaz;
			}
			set
			{
				if ((this._ID_Zakaz != value))
				{
					this.OnID_ZakazChanging(value);
					this.SendPropertyChanging();
					this._ID_Zakaz = value;
					this.SendPropertyChanged("ID_Zakaz");
					this.OnID_ZakazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nomer_Tel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nomer_Tel
		{
			get
			{
				return this._Nomer_Tel;
			}
			set
			{
				if ((this._Nomer_Tel != value))
				{
					this.OnNomer_TelChanging(value);
					this.SendPropertyChanging();
					this._Nomer_Tel = value;
					this.SendPropertyChanged("Nomer_Tel");
					this.OnNomer_TelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[adres dostavki]", Storage="_adres_dostavki", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string adres_dostavki
		{
			get
			{
				return this._adres_dostavki;
			}
			set
			{
				if ((this._adres_dostavki != value))
				{
					this.Onadres_dostavkiChanging(value);
					this.SendPropertyChanging();
					this._adres_dostavki = value;
					this.SendPropertyChanged("adres_dostavki");
					this.Onadres_dostavkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[adres otpravki]", Storage="_adres_otpravki", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string adres_otpravki
		{
			get
			{
				return this._adres_otpravki;
			}
			set
			{
				if ((this._adres_otpravki != value))
				{
					this.Onadres_otpravkiChanging(value);
					this.SendPropertyChanging();
					this._adres_otpravki = value;
					this.SendPropertyChanged("adres_otpravki");
					this.Onadres_otpravkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statyz_zakaz", DbType="Bit NOT NULL")]
		public bool Statyz_zakaz
		{
			get
			{
				return this._Statyz_zakaz;
			}
			set
			{
				if ((this._Statyz_zakaz != value))
				{
					this.OnStatyz_zakazChanging(value);
					this.SendPropertyChanging();
					this._Statyz_zakaz = value;
					this.SendPropertyChanged("Statyz_zakaz");
					this.OnStatyz_zakazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tsena_proyeezda", DbType="Int NOT NULL")]
		public int Tsena_proyeezda
		{
			get
			{
				return this._Tsena_proyeezda;
			}
			set
			{
				if ((this._Tsena_proyeezda != value))
				{
					this.OnTsena_proyeezdaChanging(value);
					this.SendPropertyChanging();
					this._Tsena_proyeezda = value;
					this.SendPropertyChanged("Tsena_proyeezda");
					this.OnTsena_proyeezdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oplata", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Oplata
		{
			get
			{
				return this._Oplata;
			}
			set
			{
				if ((this._Oplata != value))
				{
					this.OnOplataChanging(value);
					this.SendPropertyChanging();
					this._Oplata = value;
					this.SendPropertyChanged("Oplata");
					this.OnOplataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
