#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Atele")]
	public partial class DataClasses4DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertZakaz(Zakaz instance);
    partial void UpdateZakaz(Zakaz instance);
    partial void DeleteZakaz(Zakaz instance);
    #endregion
		
		public DataClasses4DataContext() : 
				base(global::WpfApp1.Properties.Settings.Default.AteleConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Zakaz> Zakaz
		{
			get
			{
				return this.GetTable<Zakaz>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zakaz")]
	public partial class Zakaz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_zakaz;
		
		private int _id_klzak;
		
		private int _id_uslzak;
		
		private System.DateTime _date_zak;
		
		private bool _status_zak;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_zakazChanging(int value);
    partial void Onid_zakazChanged();
    partial void Onid_klzakChanging(int value);
    partial void Onid_klzakChanged();
    partial void Onid_uslzakChanging(int value);
    partial void Onid_uslzakChanged();
    partial void Ondate_zakChanging(System.DateTime value);
    partial void Ondate_zakChanged();
    partial void Onstatus_zakChanging(bool value);
    partial void Onstatus_zakChanged();
    #endregion
		
		public Zakaz()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zakaz", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_zakaz
		{
			get
			{
				return this._id_zakaz;
			}
			set
			{
				if ((this._id_zakaz != value))
				{
					this.Onid_zakazChanging(value);
					this.SendPropertyChanging();
					this._id_zakaz = value;
					this.SendPropertyChanged("id_zakaz");
					this.Onid_zakazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_klzak", DbType="Int NOT NULL")]
		public int id_klzak
		{
			get
			{
				return this._id_klzak;
			}
			set
			{
				if ((this._id_klzak != value))
				{
					this.Onid_klzakChanging(value);
					this.SendPropertyChanging();
					this._id_klzak = value;
					this.SendPropertyChanged("id_klzak");
					this.Onid_klzakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uslzak", DbType="Int NOT NULL")]
		public int id_uslzak
		{
			get
			{
				return this._id_uslzak;
			}
			set
			{
				if ((this._id_uslzak != value))
				{
					this.Onid_uslzakChanging(value);
					this.SendPropertyChanging();
					this._id_uslzak = value;
					this.SendPropertyChanged("id_uslzak");
					this.Onid_uslzakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_zak", DbType="Date NOT NULL")]
		public System.DateTime date_zak
		{
			get
			{
				return this._date_zak;
			}
			set
			{
				if ((this._date_zak != value))
				{
					this.Ondate_zakChanging(value);
					this.SendPropertyChanging();
					this._date_zak = value;
					this.SendPropertyChanged("date_zak");
					this.Ondate_zakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_zak", DbType="Bit NOT NULL")]
		public bool status_zak
		{
			get
			{
				return this._status_zak;
			}
			set
			{
				if ((this._status_zak != value))
				{
					this.Onstatus_zakChanging(value);
					this.SendPropertyChanging();
					this._status_zak = value;
					this.SendPropertyChanged("status_zak");
					this.Onstatus_zakChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
