<?xml version="1.0" encoding="utf-8"?><Database Name="Atele" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-R346Q9L;Initial Catalog=Atele;Integrated Security=True" SettingsObjectName="WpfApp1.Properties.Settings" SettingsPropertyName="AteleConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Klients" Member="Klients">
    <Type Name="Klients">
      <Column Name="id_kl" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fio_kl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tel_kl" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="statys_kl" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>