#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Atele")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertKlients(Klients instance);
    partial void UpdateKlients(Klients instance);
    partial void DeleteKlients(Klients instance);
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::WpfApp1.Properties.Settings.Default.AteleConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klients> Klients
		{
			get
			{
				return this.GetTable<Klients>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klients")]
	public partial class Klients : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_kl;
		
		private string _fio_kl;
		
		private string _tel_kl;
		
		private bool _statys_kl;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_klChanging(int value);
    partial void Onid_klChanged();
    partial void Onfio_klChanging(string value);
    partial void Onfio_klChanged();
    partial void Ontel_klChanging(string value);
    partial void Ontel_klChanged();
    partial void Onstatys_klChanging(bool value);
    partial void Onstatys_klChanged();
    #endregion
		
		public Klients()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kl", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_kl
		{
			get
			{
				return this._id_kl;
			}
			set
			{
				if ((this._id_kl != value))
				{
					this.Onid_klChanging(value);
					this.SendPropertyChanging();
					this._id_kl = value;
					this.SendPropertyChanged("id_kl");
					this.Onid_klChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fio_kl", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fio_kl
		{
			get
			{
				return this._fio_kl;
			}
			set
			{
				if ((this._fio_kl != value))
				{
					this.Onfio_klChanging(value);
					this.SendPropertyChanging();
					this._fio_kl = value;
					this.SendPropertyChanged("fio_kl");
					this.Onfio_klChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel_kl", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tel_kl
		{
			get
			{
				return this._tel_kl;
			}
			set
			{
				if ((this._tel_kl != value))
				{
					this.Ontel_klChanging(value);
					this.SendPropertyChanging();
					this._tel_kl = value;
					this.SendPropertyChanged("tel_kl");
					this.Ontel_klChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statys_kl", DbType="Bit NOT NULL")]
		public bool statys_kl
		{
			get
			{
				return this._statys_kl;
			}
			set
			{
				if ((this._statys_kl != value))
				{
					this.Onstatys_klChanging(value);
					this.SendPropertyChanging();
					this._statys_kl = value;
					this.SendPropertyChanged("statys_kl");
					this.Onstatys_klChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
