#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Atele")]
	public partial class DataClasses3DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertUslugi(Uslugi instance);
    partial void UpdateUslugi(Uslugi instance);
    partial void DeleteUslugi(Uslugi instance);
    #endregion
		
		public DataClasses3DataContext() : 
				base(global::WpfApp1.Properties.Settings.Default.AteleConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses3DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Uslugi> Uslugi
		{
			get
			{
				return this.GetTable<Uslugi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uslugi")]
	public partial class Uslugi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_uslugi;
		
		private string _name_uslugi;
		
		private int _cena_uslugi;
		
		private bool _status_uslugi;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_uslugiChanging(int value);
    partial void Onid_uslugiChanged();
    partial void Onname_uslugiChanging(string value);
    partial void Onname_uslugiChanged();
    partial void Oncena_uslugiChanging(int value);
    partial void Oncena_uslugiChanged();
    partial void Onstatus_uslugiChanging(bool value);
    partial void Onstatus_uslugiChanged();
    #endregion
		
		public Uslugi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_uslugi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_uslugi
		{
			get
			{
				return this._id_uslugi;
			}
			set
			{
				if ((this._id_uslugi != value))
				{
					this.Onid_uslugiChanging(value);
					this.SendPropertyChanging();
					this._id_uslugi = value;
					this.SendPropertyChanged("id_uslugi");
					this.Onid_uslugiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_uslugi", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string name_uslugi
		{
			get
			{
				return this._name_uslugi;
			}
			set
			{
				if ((this._name_uslugi != value))
				{
					this.Onname_uslugiChanging(value);
					this.SendPropertyChanging();
					this._name_uslugi = value;
					this.SendPropertyChanged("name_uslugi");
					this.Onname_uslugiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena_uslugi", DbType="Int NOT NULL")]
		public int cena_uslugi
		{
			get
			{
				return this._cena_uslugi;
			}
			set
			{
				if ((this._cena_uslugi != value))
				{
					this.Oncena_uslugiChanging(value);
					this.SendPropertyChanging();
					this._cena_uslugi = value;
					this.SendPropertyChanged("cena_uslugi");
					this.Oncena_uslugiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_uslugi", DbType="Bit NOT NULL")]
		public bool status_uslugi
		{
			get
			{
				return this._status_uslugi;
			}
			set
			{
				if ((this._status_uslugi != value))
				{
					this.Onstatus_uslugiChanging(value);
					this.SendPropertyChanging();
					this._status_uslugi = value;
					this.SendPropertyChanged("status_uslugi");
					this.Onstatus_uslugiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
